### ISSUE TITLE
Error: Invalid CSS after "...0%, -50%, 0); }": expected selector or at-rule, was "}"

### ISSUE THREAD

**Issue by daragao** [qqnc/md-chips-select#5]
There is an error in [md-chips-select.css](https://github.com/qqnc/md-chips-select/blob/master/md-chips-select.css#L230) on line 230.
The `.remove` class has one `}` too many at the end. Although it works when you link the css file in a html, it doesn't allow for it to be imported into SASS.
It is a simple fix it seems :)

**Comment by nch3ng** [comment]
thanks
